stages:
  - test
  - report
  - deploy

docker-test:
  image: docker/compose:latest
  stage: test
  allow_failure: true
  services:
    - docker:dind
  variables:
    TESTNG_FAILED_XML: jar/test-output/testng-failed.xml
  script:
    - apk add tree
    - docker-compose up -d --build --scale chrome=3
    - docker wait test-run
    - chmod +x ./script.sh
    - ./script.sh
    - |
      if [[ -f "$TESTNG_FAILED_XML" ]]; then
        echo "Test failures observed as TestNG-Failed file exists."
      else
        echo "All tests passed Successfully."
      fi
    - echo "Files:"
    - ls
    - find . -type d > output.txt
  after_script:
    - docker-compose down
  artifacts:
    reports:
      junit:
        - jar/test-output/junitreports/TEST-*.xml
    paths:
      - output.txt
      - jar/test-output/
      - jar/src/test/resources/results/
    when: always
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile
        - docker-compose.yml

pages:
  image: node:16-slim
  stage: deploy
  script:
    - mkdir -p .public
    - cp -r * .public
    - mv ./report public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
  environment:
    name: production/${CI_PROJECT_NAME}/${CI_COMMIT_REF_NAME}
    url: https://${CI_PROJECT_NAME}.gitlab.io