
name: github-ci
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        uses: actions/checkout@v3

      - name: Step two
        run: env | sort

  windows-build:
    runs-on: windows-latest
    steps:
      - name: Step one
        uses: actions/checkout@v3

      - name: Step two
        run: "Get-ChildItem Env: | Sort-Object Name"


  mac-build:
    runs-on: macos-latest
    steps:
      - name: Step one
        uses: actions/checkout@v3

  display:
    runs-on: ubuntu-latest
    needs: [ubuntu-build, windows-build, mac-build]
    steps:
      - name: Final Step
        run: echo Final step completed...
